# template for data processing plugin
x-data-processing-plugin: &data-processing-plugin
  image: ghcr.io/cops-lab/data-processing:0.0.16-beta
  restart: "unless-stopped"
  depends_on: [ "kafka", "metadata-db" ]
  environment:
    PG_PWD: ${DB_PWD}

services:

  ## INFRASTRUCTURE

  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - 9092:9092
    volumes: [
      "./volumes/kafka:/bitnami/kafka"
    ]
    environment:
      # Kraft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Custom
      - KAFKA_CFG_NUM_PARTITIONS=10

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "unless-stopped"
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - kafka

  metadata-db:
    build:
      context: metadata-db
      dockerfile: Dockerfile
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: fasten1234
    ports: [ 5432:5432 ]
    volumes: [
      "./volumes/metadata-db/data:/var/lib/postgresql/data"
    ]
  
  ## FASTEN SERVICES

  easy-index:
    #profiles: ["disabled"]
    image: ghcr.io/cops-lab/maven-easy-index:0.0.2-beta
    restart: "unless-stopped"
    volumes: [
      "./caches/easy-index/:/cache"
    ]

  maven-crawler: 
    <<: *data-processing-plugin
    profiles: ["disabled"]
    volumes: [
      "./volumes/:/data/"
    ]
    command: [
      "--run", "eu.f4sten.mavencrawler.Main",
      "--mc.easyIndexUrl", "http://easy-index:8080/",
      "--mc.firstConsideredIndex", "323",
      "--instanceId", "mc1",
      # default values:
      "--baseDir", "/data",
      "--kafka.url", "${KAFKA_URL}",
      "--db.url", "${DB_URL}",
      "--db.user", "${DB_USER}"
    ]

  pom-analyzer:
    <<: *data-processing-plugin
    #profiles: ["disabled"]
    volumes: [
      "./caches/.m2/:/root/.m2",
      "./volumes/:/data/"
    ]
    command: [
      "--run", "eu.f4sten.pomanalyzer.Main",
      "--instanceId", "pa1",
      # default values:
      "--baseDir", "/data",
      "--kafka.url", "${KAFKA_URL}",
      "--db.url", "${DB_URL}",
      "--db.user", "${DB_USER}"
    ]

  dep-graph-resolver:
    <<: *data-processing-plugin
    #profiles: ["disabled"]
    volumes: [
      "./volumes/:/data/"
    ]
    command: [
      "--run", "eu.f4sten.depgraph.Main",
      "--instanceId", "dg1",
      # default values:
      "--baseDir", "/data",
      "--kafka.url", "${KAFKA_URL}"
    ]
    ports:
      - "18081:8080"
